In [1]:
import tensorflow as tf

In [3]:
print(tf.config.list_physical_devices('GPU'))

[]


In [4]:
# This line creates a Dense layer with 100 neurons.
# It doesn't specify an input shape, meaning it can 
# receive any input shape as long as the last dimension 
# reflects the number of features (unknown in this case).
layer = tf.keras.layers.Dense(100)
# This line creates another Dense layer with 10 neurons.
# This time, it explicitly specifies the input shape as (None, 5).
# None indicates the batch size can vary.
# 5 indicates the input must have 5 features in its last dimension.
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

(None, 5):This means the layer expects input tensors with any batch size (None) and 5 features in the last dimension.

In [5]:
# To use a layer, simply call it.
layer(tf.zeros([10, 5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [6]:
#  refers to the trainable variables associated with the Dense layer you defined. 
# These variables are the weights and 
# biases that the layer learns during training to map its input to its output.
layer.variables


[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.0434404 , -0.53541714,  0.34415454, -0.4460123 , -0.36376977,
         -0.06235719, -0.57802457, -0.6229897 , -0.26414382, -0.5380404 ],
        [-0.26569697,  0.35765678,  0.34695196, -0.6214969 ,  0.41504806,
          0.4532482 , -0.01825029, -0.41375244, -0.5011643 , -0.02379256],
        [-0.19553131, -0.46126896, -0.14279959, -0.5574102 ,  0.35426027,
          0.15109932,  0.17279696, -0.5446816 ,  0.19286114,  0.4783172 ],
        [ 0.3710732 ,  0.35513288,  0.23010528,  0.02069855,  0.4579851 ,
         -0.5703467 ,  0.18097109,  0.14266962, -0.27272254,  0.25204813],
        [-0.46464032,  0.15646714,  0.07947612, -0.31822678, -0.00378495,
          0.23303318, -0.124753  ,  0.23110938,  0.25322384,  0.06020439]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [7]:
layer.kernel, layer.bias


(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.0434404 , -0.53541714,  0.34415454, -0.4460123 , -0.36376977,
         -0.06235719, -0.57802457, -0.6229897 , -0.26414382, -0.5380404 ],
        [-0.26569697,  0.35765678,  0.34695196, -0.6214969 ,  0.41504806,
          0.4532482 , -0.01825029, -0.41375244, -0.5011643 , -0.02379256],
        [-0.19553131, -0.46126896, -0.14279959, -0.5574102 ,  0.35426027,
          0.15109932,  0.17279696, -0.5446816 ,  0.19286114,  0.4783172 ],
        [ 0.3710732 ,  0.35513288,  0.23010528,  0.02069855,  0.4579851 ,
         -0.5703467 ,  0.18097109,  0.14266962, -0.27272254,  0.25204813],
        [-0.46464032,  0.15646714,  0.07947612, -0.31822678, -0.00378495,
          0.23303318, -0.124753  ,  0.23110938,  0.25322384,  0.06020439]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [8]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    # the number of neurons in this custom Dense layer
    self.num_outputs = num_outputs

  # It's called during the model build phase to create trainable variables 
  # (weights and biases) for the layer based on the input shape it receives.
  def build(self, input_shape):
    # creates a trainable weight matrix named kernel
    # 
    self.kernel = self.add_weight("kernel",
                                  shape=[int(input_shape[-1]), # last dimension of the input shape
                                         self.num_outputs])
  # Forward
  def call(self, inputs):
    # performs matrix multiplication between the input and 
    # the weight matrix (kernel) to produce the output.
    return tf.matmul(inputs, self.kernel)

layer = MyDenseLayer(10)

In [9]:
_ = layer(tf.zeros([10, 5])) # Calling the layer `.builds` it.

In [10]:
# Define some sample data
inputs = tf.random.uniform([32, 5])  # Batch size 32, 5 features

# Create your custom layer
layer = MyDenseLayer(10)

# Build a model using your custom layer
model = tf.keras.Sequential([layer])

# Compile the model
model.compile(loss="mse", optimizer="adam")

# Make predictions on the sample data
predictions = model.predict(inputs)

# Print the first few predictions
print(predictions[:5])



1/1 [==============================] - 0s 143ms/step
[[-0.06624338 -0.6830077  -0.12006319  0.17663945 -0.2269658   0.29198703
  -0.27604198 -0.5744072  -0.1723164  -0.43104485]
 [-0.12092712 -0.39491507 -0.01560635  0.01157218 -0.089439   -0.05295243
  -0.06646307 -0.43210632 -0.16559185 -0.33649725]
 [ 0.10992171 -0.8105143  -0.3752871   0.18966271 -0.15153775 -0.3845326
   0.48044533 -0.43506896 -0.71579933 -0.40534148]
 [ 0.09723689 -0.42628223 -0.4318757   0.11764948 -0.3896391  -0.3078237
   0.24957472  0.04947088 -0.3371947  -0.12522113]
 [ 0.05393583 -0.627409   -0.61968523  0.20036758 -0.4547115  -0.6969608
   0.7152791  -0.06261729 -0.6786833  -0.30145714]]


In [ ]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name='')
    filters1, filters2, filters3 = filters

  # Creates three convolutional layers (conv2a, conv2b, conv2c) 
  # with different filter sizes and a 1x1 kernel size for the first
  # and last layers.
  # Adds batch normalization layers (bn2a, bn2b, bn2c) after 
  # each convolutional layer for normalization and regularization.
    
    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()

  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2c(x)
    x = self.bn2c(x, training=training)

    x += input_tensor
    return tf.nn.relu(x)


block = ResnetIdentityBlock(1, [1, 2, 3])